jenkins:
    user: ${USER_ID}
    environment:
        - SERVICE_NAME=SPACENAME-ci

testintegration:
    environment:
        - SERVICE_NAME=SPACENAME-testintegration
omero:
    environment:
        - SERVICE_NAME=SPACENAME-omero

nginx:
    environment:
        - SERVICE_NAME=SPACENAME-nginx

nginxjenkins:
    environment:
        - SERVICE_NAME=SPACENAME-nginxjenkins
